### ISSUE TITLE
Allow user to force vertical alignment of editor & console

### ISSUE THREAD

**Issue by kpalway** [cs136/seashell#133]

**Comment by kpalway** [comment]
UI-wise: User drags title bar of the console window to the bottom and it snaps down there

**Comment by thadeaus** [comment]
I created a fullscreen mode instead, would we be able to remove this ticket, or do we still want to implement the forced vertical allignment?

**Comment by kpalway** [comment]
I think we should still have the vertical alignment as an option.

**Comment by e45lee** [comment]
This has now been fixed in master.
