### ISSUE TITLE
3 Digit Line Numbers Spill out of Gutter 

### ISSUE THREAD

**Issue by phil-bystrican** [cs136/seashell#141]
When the line number get to be larger than 2 digits they spill out of the gutter and into the code section on Firefox 35 and Safari 8.0.3 (untested in Chrome).

![screen shot 2015-01-21 at 1 09 00 am](https://cloud.githubusercontent.com/assets/10040177/5831925/42c84a50-a10a-11e4-9b1c-7a87f9690b95.png)

**Comment by Gibstick** [comment]
There are a bunch of small issues like this with the non-default themes. I can't reproduce this issue on the default Elegant theme, Firefox 36 beta on Windows 8.1.

**Comment by e45lee** [comment]
We've made a minor change that should mitigate this issue in an upcoming Seashell deployment.
