### ISSUE TITLE
[seashell-unstable] Opening a project does not open an assignment

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#156]
Not necessarily a bug per-se, but the current version of Seashell opens some file when opening a project. The new version should at least keep this behavior, or even better, remember the last-opened file. 

Or maybe this is just intended behavior; in that case, disregard.

**Comment by kpalway** [comment]
I think not opening a file is better than opening an arbitrary file (or the "first" file), but it would be nice to remember the last file opened in that assignment/question. We do plan to implement this.
