### ISSUE TITLE
[seashell-unstable] add line-length warning 

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#157]
The line:col indicator should change style (to red font, for example) when the current line is over 80 characters long. Seems like Angular is well-suited for this task.

Additionally/alternatively, CodeMirror has a "rulers" addon that can add a vertical ruler at 80 characters: http://codemirror.net/doc/manual.html#addon_rulers. This would match the behavior of other editors.

I'd do all these things myself but I'm having some trouble getting my own instance of Seashell (hosted on my VPS) to connect to Waterloo's servers.

**Comment by kpalway** [comment]
Good idea, we can probably implement this very soon.

**Comment by Gibstick** [comment]
Perhaps the ruler would be more useful if line wrapping were turned off?
https://github.com/cs136/seashell/blob/7d6ffed1f7ba2f8151b1fd469583388a5f0e9597/src/frontend/frontend/frontend.js#L103

**Comment by Gibstick** [comment]
There's still some odd formatting going on, maybe related to line wrapping. Rulers aren't showing up.
![screenshot](https://cloud.githubusercontent.com/assets/1320418/6179508/dc25b072-b2e7-11e4-9070-4ab0df603d31.png)
Firefox 36.0

**Comment by e45lee** [comment]
Yes, we're aware that the ruler won't show up if the editor is less than 80 lines wide, and line-wrapping is enabled.  I think that people would prefer that line wrapping is enabled, and the flashing red column number should be sufficient warning.
