### ISSUE TITLE
[seashell-unstable] Indent-all missing

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#168]
Hi, a while ago I authored https://github.com/cs136/seashell/commit/02181665ba9999e2764acf13ff1b6c567b3557d9 but it seems like it didn't get ported over to the new editor yet. I'm not familiar with Angular, or else I'd add it in myself again. Purely anecdotal evidence suggests that this would be a very welcome feature, based on feedback from some friends.

**Comment by e45lee** [comment]
Unfortunately, this is low on our list of things to do (one of which is to release the cleaned-up frontend out).

We will try to address this soon, however - but that'll have to wait until we deploy the new version of Seashell.
