### ISSUE TITLE
[seashell-unstable] Cannot kill an infinite loop that has output

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#170]
As CS136 transitions from recursion to loops I'm sure there will be people who end up with infinite loops in their program. As of now, a program with an infinite loop that doesn't otherwise crash (eg. segfault) cannot be killed, and locks up the "Run" button even for other files too.

Steps to reproduce:
  1. Create a C file with an infinite loop with output
  2. Run it
  3. Click Stop

Expected behaviour:
- Program is kill

Actual behaviour:
- Program keeps running, until some time limit 
- Firefox may hang, giving a script not responding warning for frontend.js:387

Workaround:
- Reload Seashell

**Comment by e45lee** [comment]
I can't reproduce this.  If you have time today [Friday, 13 Feb], can you please swing by the tutor's center sometime this afternoon [between 2-4], or attach a test case so we can attempt to reproduce this on our end?

**Comment by Gibstick** [comment]
Sorry, I forgot an important detail. It only happens on an infinite loop with output AND it can cause Firefox to hang. I noticed this when a friend's Seashell instance started to hang the browser on infinite output for the shapes problem.
```C
#include <stdio.h>

int main(void) {
  while(1) printf("\n");
}
```

Sometimes, Firefox is able to recover and give a "script not responding" dialog pointing to frontend.js:387.

**Comment by e45lee** [comment]
No, that's enough information for us.
