### ISSUE TITLE
Auto load most recently worked on file in a question

### ISSUE THREAD

**Issue by zanwenhuahao** [cs136/seashell#180]
When clicking on question for an assignment, the most recently worked on question does not automatically load. It is blank underneath the menu bar, this is a little frustrating as I have to look through (and if the question had multiple files) the files to find which one I was working on just before (and sometimes people don't pay attention to the name of the file they were working on). Could we have this feature back please?

**Comment by e45lee** [comment]
This is a duplicate of #79
