### ISSUE TITLE
Pasting does not trigger autosave on empty files

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#184]
Steps to reproduce:
1. Have some content in clipboard.
2. Have an assignment with multiple files.
3. Have an empty file open.
4. Click to focus the editor, then press Ctrl+V or use menus to paste.
5. Click to open any other file.
6. Re-open the first file.

Expected behavior: First file should contain the content we pasted

Actual behavior: File is empty

Workaround: Type something after pasting

Noticed this after trying to copy-paste some tests for assignment 5.

Affects both the stable and unstable branch.

**Comment by kpalway** [comment]
This appears to be fixed on master now.
