### ISSUE TITLE
Console too thin (height-wise) when editor takes up whole horizontal

### ISSUE THREAD

**Issue by zanwenhuahao** [cs136/seashell#202]
Sometimes in my demo (and I noticed in Reaz's demo as well), we like to zoom in on the webpage to make it about 120-150%, in which the editor panel automatically takes up the whole horizontal space and the console gets displaced to the bottom of the editor. However the console is about (literally) 2 inches high, and cannot show more than 3-4 lines of output, makes demo seeing console message very hard.

Can we add a function such that if the console comes to the bottom, then we can pull the console bigger or smaller? (would this be resolved once the button to relocate console is added in the next update?)

**Comment by thadeaus** [comment]
This is a feature we are working on currently. This should be fixed soon.

**Comment by thadeaus** [comment]
https://github.com/cs136/seashell/issues/202#
