### ISSUE TITLE
vim "Ctrl-R redo" shortcut conflicting with seashell "Ctrl-R run" hotkey

### ISSUE THREAD

**Issue by pmelanson** [cs136/seashell#204]
In seashell Ctrl-R is bound to run the current file. I tried poking around the frontend code, but I can't find the string "Ctrl-R" in the seashell repo, so I don't know what relevant lines to look at. The side effect of this is that when I press Ctrl-R I undo one change, but also run the file.

The proposed fix would be to change the default vim keybinding from "`<C-r>` redo" to something else intuitive, perhaps "Shift-U redo" where undo is bound to "u undo". Shift-U probably isn't bound to anything, so there shouldn't be any conflicts.

Ofc, CodeMirror only serves the default vim keybinding, so I don't know if there's an elegant solution apart from "read keybinding: if keybinding == C-r keybinding = U, else use-keybinding".

I could just not use undo, but that's like ehhhhhh.

**Comment by e45lee** [comment]
Yeah, we're aware of this issue; as far as I'm aware, the vim bindings are quite monolithic and hard to change from CodeMirror.  What will _probably_ happen is that the binding for Run will change, but we probably can't change that (for consistency) this term...

And the string is ctrl+r.

**Comment by pmelanson** [comment]
Thanks for taking a look, I just wanted to make sure there was an official bug report, and searching the issue tracker returned nothing. 

Also yeah, I think I described Ctrl-r no less than three different ways in the OP. Ah well.

**Comment by kpalway** [comment]
I've removed the Ctrl-R and Ctrl-U run/test bindings in Vim mode only, so currently no run/test shortcut exists for Vim mode users. This is probably the "nicest" solution that exists, but if anyone would like to propose something else, feel free.

Closing this issue for now.
