### ISSUE TITLE
File upload should normalize newlines

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#210]
For some assignments in CS 136 we are provided with .in and .expect files for testing. If these are copy-pasted into Seashell, everything works fine (after working around that copy-paste bug), but if they are uploaded, then they will retain their newline formats. If the file has Windows CRLF newlines, tests will always fail.

Of course you could tell the ISAs/instructors to not provide files with Windows line endings, but it's not unreasonable to have people writing their own tests locally in notepad and then uploading them.

Workaround: same as the copy-paste, just force a save by editing the file after uploading.

**Comment by e45lee** [comment]
We could add an option to normalize line endings on file upload.  Also, isn't the copy-paste bug fixed?

**Comment by Gibstick** [comment]
Yes it has--when I posted this I was talking in context of the stable build. My mistake.
