### ISSUE TITLE
Parens in comments still count for paren highlighting

### ISSUE THREAD

**Issue by pmelanson** [cs136/seashell#215]
The frontend paren highlighter detects parens even when they are commented out, which I believe is not the intended behaviour.

Consider the following file:

```
if (cond) {
//printf("conded");
//}
cond = false;
}
```

The final brace is red highlighted, since the paren finder detects the brace on line 3 as being a closed brace. This might throw off people who comment out code.

(btw this paren highlighting stuff? Super cool.)

**Comment by e45lee** [comment]
Yeah, this is a CodeMirror issue -- we can't fix this.
