### ISSUE TITLE
Remember Scroll Position on File Change

### ISSUE THREAD

**Issue by thadeaus** [cs136/seashell#217]
When working on larger projects that make you have to scroll excessive amounts, when you change between the .h file and .c files you have to re-scroll to the place you were at before. Is there some way we can remember the line that we were scrolled to in the previous file opened?

**Comment by Gibstick** [comment]
http://codemirror.net/doc/manual.html#getCursor and setCursor. getCursor to save the current position in file, setCursor to go there.

Now to figure out where to save this.

**Comment by thadeaus** [comment]
I have gotten it to save the position, but I cannot make the setCursor() function work for some reason. I can push my broken branch to my repo if you want to see.

**Comment by thadeaus** [comment]
Re-opened to keep it so that we can make the data persist on the backend so that if you disconnect the information still stays.

**Comment by Gibstick** [comment]
Maybe look how the recent file is being stored in the backend, and follow along with that.

**Comment by thadeaus** [comment]
A Racket function needs to be changed on the backend to save more information for the different files.

**Comment by kpalway** [comment]
I don't think saving this information on the backend will give any real benefit. Seems like something that should just be cached locally.
