### ISSUE TITLE
Redesign Landing Page

### ISSUE THREAD

**Issue by thadeaus** [cs136/seashell#218]
A few other issues involved with this:
- Make landing page items load by last project viewed
- Make landing page items load faster

**Comment by thadeaus** [comment]
I have the new landing page almost complete. I was wondering if anyone could let me know if I should delete the function calls to get the questions for each project, and also I was wondering about getting the date modified for each project. Where would I access this info?

**Comment by e45lee** [comment]
You will probably have to change https://github.com/cs136/seashell/blob/master/src/frontend/frontend/frontend.js#L1358-L1366

**Comment by thadeaus** [comment]
I was wondering if anyone had any insight on how I could change the modification time on the project directory so they show up properly. The one thing that I could think of is create an empty file, and then delete it immediately after but I feel like that would be more intensive than we want.

I also tried looking for a "touch" command in racket but couldn't find any.

**Comment by e45lee** [comment]
You're going to have to make a FFI call to utimensat(2).  I can show you how this is done Wednesday.
