### ISSUE TITLE
Context-sensitive console, w/better test result formatting

### ISSUE THREAD

**Issue by kpalway** [cs136/seashell#265]

**Comment by e45lee** [comment]
Still need to work on better test output display.

**Comment by kpalway** [comment]
Aren't you the only one who wanted this feature? Maybe we could just have coloured output with the terminal emulator.

**Comment by e45lee** [comment]
Yeah I'm not sure who wanted it (probably me, but it's been 2 years).  I was mainly thinking coloured output here also.

**Comment by e45lee** [comment]
We've implemented colours in the terminal; this should help.

**Comment by kpalway** [comment]
The colours don't actually display right now. Our xterm.js instance swallows them for some reason. I also added bolding, which does work.

**Comment by e45lee** [comment]
Oh, I fixed that in 6f9704a6c02669376e28bfa6c49be5c9ec23aae6.
