### ISSUE TITLE
Get Rid of .O files and replace with Bytecode

### ISSUE THREAD

**Issue by thadeaus** [cs136/seashell#279]
So that we do not need to prepare multiple .o files for the different environments.

**Comment by e45lee** [comment]
This is possible; use clang -c -emit-llvm to generate bitcode objects, but I'm not entirely sure if the generated bitcode is portable between platforms...

**Comment by e45lee** [comment]
Bitcode is not portable between platforms (as pointer size assumptions are hard-coded in it),
but I think we can at least share bitcode between the offline-mode compiler and the online compiler.

Closing as WONTFIX.
