### ISSUE TITLE
Console Discoverability Suggestions

### ISSUE THREAD

**Issue by bruceiv** [cs136/seashell#281]
It is quite clearly explained how to use the console in the user guide, but for someone who didn't read the user guide first, it's not immediately obvious how to actually enter text into the console.

I think it would be less surprising to users if you could actually enter text directly in the console window, or, failing that, if the console didn't show a text entry cursor when you clicked inside it and if the text box at the bottom was more obviously styled as a text entry box.

**Comment by thadeaus** [comment]
A couple of points to this, it does immediately move your cursor down to the console text enter, and has the arrow suggesting people to enter text. The console also won't let you type anything above right now.

One simple fix for this would probably to have filler text saying, "Type Here and Press Enter". Would this be a good solution to the issue?

**Comment by thadeaus** [comment]
I added placeholder text to the console. So I am closing this issue. If that is not enough please bring it back up.
