### ISSUE TITLE
Support logins from frontend.html

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#336]
We'll need to do work for this anyways (i.e from transitioning from offline -> online mode), and a lot of students are confused that they can't just bookmark the Seashell frontend.html page.

**Comment by e45lee** [comment]
#335 is probably experiencing this issue.

**Comment by michaelmior** [comment]
This seems to be already resolved. I get the message "Something bad happened! Try reconnecting again, or logging in again." with a link to the login screen.

**Comment by e45lee** [comment]
I don't remember right now if this refreshes the list of assignments properly after logging in; I've heard reports that when people try to log in this way, the login works, but no assignments are listed, and it takes a refresh before they show up again.

**Comment by michaelmior** [comment]
This is the primary way I log in to Seashell since it's the first thing that comes up when I start typing in Chrome. I haven't noticed any issues.

**Comment by e45lee** [comment]
Great then!  I'll close this issue.
