### ISSUE TITLE
Disallow creating undeletable assignments.

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#364]

**Comment by e45lee** [comment]
We should tag (in the settings file) if a project is deletable or not; student created assignments will be missing this tag, and will be deletable, but templates that we create will have this tag set.

**Comment by YLiLarry** [comment]
Is this a bug? How do I create a undeleteable in the current version? (is undeleteable a word?)

**Comment by e45lee** [comment]
Right now if you create "A<number>" I think the UI prevents you from deleting that assignment/project -- even though you made it.

**Comment by kpalway** [comment]
Because it hasn't been fixed?

**Comment by e45lee** [comment]
I think we decided to hide the delete button and to make all projects delectable -- with the new snapshot system this shouldn't be too big of a deal.
