### ISSUE TITLE
Files named with 'single quotes' canot be opened / deleted

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#384]
Any number of ''''''

**Comment by Gibstick** [comment]
Workaround: https://www.student.cs.uwaterloo.ca/~s455wang/cs136/fix-quotes/

**Comment by Gibstick** [comment]
Possible regression: files with commas cannot be opened.

**Comment by Gibstick** [comment]
Need to use decodeURIComponent instead of decodeURI

**Comment by cs136** [comment]
This is fixed.
