### ISSUE TITLE
Allow runtime-files-path to be configurable

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#437]
The compiler stores binaries in (runtime-files-path).  This should be configurable so the CLI tool doesn't need ~/.seashell/runtime-files to exist.

**Comment by yc2lee** [comment]
Do you have a preference for where the user would configure this? (some config file setting or option command line argument or something else...)

**Comment by e45lee** [comment]
We store settings in https://github.com/cs136/seashell/blob/master/src/collects/seashell-config.rkt.in

**Comment by e45lee** [comment]
Nick fixed this as of #438.
