### ISSUE TITLE
Racket common files.

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#456]
Hi everyone,

The Seashell team met yesterday and discussed all of the input we've
received over the past couple weeks. Here's an explanation of the
tentative decisions we made so there are no surprises:

"/common" Folder: There is currently a discrepancy as to how files in
the /common folder can be accessed in Racket vs. in C. Our solution
will be to "flatten" the structure so all files in the /common folder
are treated as if they are in each individual question folder (so we
will have to copy these when we compile/run). This is consistent with
what currently happens when the student submits to Marmoset. We will
have to enforce that no question folder can contain a file with the
same name as a file in /common.

Refreshing Assignment Skeletons: When a project is opened, Seashell
will search for any files from the skeleton that are missing, and
replace any that it does not find with the fresh file from the
skeleton (perhaps a button will be added to do this without re-opening
the project). This way, if a student wants to get the fresh file, they
can rename or delete their existing file and get the fresh one. If the
course staff needs to change a skeleton file, there are a couple of
options: Change the file in the skeleton and request that all students
rename their in-progress file and refresh; or add a new file to the
skeleton which will be loaded the next time the student opens the
project. Either way the work of merging these changes is done by the
student.

If you have any questions or concerns about these points, let me know.

Thanks,
Kaleb

**Comment by YLiLarry** [comment]
Ok I need meet up with you guys in campus. Where can I find you?

**Comment by yc2lee** [comment]
Hey @YLiLarry I'm supposed to help with this issue. We can meet in my office or somewhere else if you want

**Comment by YLiLarry** [comment]
I can go to your office. Do you have time after 3?

**Comment by yc2lee** [comment]
I'll be in my office at 3 but I might not have time until 4 today

**Comment by YLiLarry** [comment]
Ok I'll see you at 4. Where is your office?

**Comment by yc2lee** [comment]
Hey Larry and I cannot find a command-line flag to /usr/bin/racket that would allow students to write something like (require "file.rkt") instead of (require "../common/file.rkt").

So, I am going to do exactly what Kaleb says. When students run a racket file, I'll create a temp directory, copy all the common files and question files there, and run /usr/bin/racket from there.

Please let me know if this will be as issue.

**Comment by e45lee** [comment]
I imagine that should work, though it might lead to some undefined behavior
with regards to files in the question directories if the student's code
writes to files there.

You'll want to make sure the current-directory parameter is set up to point
to the question folder not the temp folder.

**Comment by yc2lee** [comment]
What is the expected behaviour if students decide to write to "../common/pq.rkt" for example?

**Comment by e45lee** [comment]
I would think that they'd expect it to overwrite pq.rkt.

On Thu, Jan 14, 2016 at 8:06 PM, yc2lee <notifications@github.com> wrote:

> What is the expected behaviour if students decide to write to
> "../common/pq.rkt" for example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cs136/seashell/issues/456#issuecomment-171834046>.
>



-- 
Edward Lee

**Comment by yc2lee** [comment]
Okay, thanks.  So (require "pq.rkt") uses the pq.rkt in common/, but file IO on "pq.rkt" will use the "pq.rkt" in the question folder.  I think this might be a bit confusing, but I don't think CS136 has file IO so this will not be a big issue.

**Comment by e45lee** [comment]
Can we copy the common/ folder into the temp folder?  This is for backwards-compatibility reasons for this term.

**Comment by YLiLarry** [comment]
sounds good.

**Comment by yc2lee** [comment]
Larry are you doing that? I was going to do it but if you are then I won't

**Comment by YLiLarry** [comment]
Np let me handle it.
