### ISSUE TITLE
You can create a directory on seashell in the project folder, and can't delete it after.

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#457]
You can create a directory on seashell in the project folder, and can't delete it after.
To reproduce the bug:
Add a file named "filename/" (the filename needs a trailing slash)
You see an error message in the frontend, but in fact, a "filename/" directory is created.
You can't delete this directory. You can't create a file with this name anymore because the directory already exists.

**Comment by yc2lee** [comment]
Hey @YLiLarry, are you doing this one? I recall you said you wanted to do this one in yesterday's meeting

**Comment by YLiLarry** [comment]
Yes. I'm doing this. 
Larry

**Comment by yc2lee** [comment]
Great thanks! I updated this and KanbanFlow
