### ISSUE TITLE
RunC dependency stuff does not link properly against files in common

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#459]
The compiler picks them up but the linker doesn't. Broken all the way back to
cf636c49dc5a9c096c13092610e7ea8165212c40
@b2coutts

**Comment by e45lee** [comment]
Well, we'll have to fix this before the next assignment comes out.  5:30
Wednesday work for everyone?

On Tue, Jan 12, 2016 at 8:27 PM, Charlie Wang <notifications@github.com>
wrote:

> The compiler picks them up but the linker doesn't. Broken all the way back
> to
> cf636c4
> <https://github.com/cs136/seashell/commit/cf636c49dc5a9c096c13092610e7ea8165212c40>
> @b2coutts <https://github.com/b2coutts>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cs136/seashell/issues/459>.
>



-- 
Edward Lee

**Comment by Gibstick** [comment]
Ye

**Comment by YLiLarry** [comment]
Wednesday 5:30 for the weekly meeting?

I'm fine with that.

Larry

**Comment by e45lee** [comment]
No, just an emergency patch for this issue.

On Tue, Jan 12, 2016 at 11:44 PM, Yu Li <notifications@github.com> wrote:

> Wednesday 5:30 for the weekly meeting?
>
> I'm fine with that.
>
> Larry
>
> > On Jan 12, 2016, at 11:42 PM, Edward Lee <notifications@github.com>
> wrote:
> >
> > Well, we'll have to fix this before the next assignment comes out. 5:30
> > Wednesday work for everyone?
> >
> > On Tue, Jan 12, 2016 at 8:27 PM, Charlie Wang <notifications@github.com>
> > wrote:
> >
> > > The compiler picks them up but the linker doesn't. Broken all the way
> back
> > > to
> > > cf636c4
> > > <
> https://github.com/cs136/seashell/commit/cf636c49dc5a9c096c13092610e7ea8165212c40
> >
> > > @b2coutts <https://github.com/b2coutts>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cs136/seashell/issues/459>.
> > >
> >
> >
> >
> > --
> > Edward Lee
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/cs136/seashell/issues/459#issuecomment-171164748>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cs136/seashell/issues/459#issuecomment-171165689>.
>



-- 
Edward Lee

**Comment by YLiLarry** [comment]
Can't be 5:30 in the morning tho no matter how you like to be early.

Larry
