### ISSUE TITLE
Disallow empty test name in "Add Test" modal

### ISSUE THREAD

**Issue by Gibstick** [cs136/seashell#463]
https://github.com/cs136/seashell/blob/master/src/frontend/frontend/modals.js#L269

**Comment by Gibstick** [comment]
error:       Bad argument: compile-and-run-project/use-runner: contract violation
  expected: path-string?
  given: ""
  in: an element of
      the 3rd argument of
      (->
       project-name?
       string?
       (listof path-string?)
       (values boolean? hash?))
  contract from:
      (function
       compile-and-run-project/use-runner)
  blaming: #%embedded:g21327:project
   (assuming the contract is correct)
  at: /u2/cs136/seashell-8117/build/src/collects/seashell/backend/project.rkt:514.18.

**Comment by e45lee** [comment]
I imagine that one can use the inline Angular/HTML5 form validation tools here.  The less JavaScript written, the better.

**Comment by Gibstick** [comment]
You're right, hold on.
