### ISSUE TITLE
Write CAS proxy CGI script

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#510]
example code here: https://github.com/cs136/seashell/blob/5116c9315ed045e1b61f05d29c33f8eabc71b6f6/src/cas.rkt

**Comment by yc2lee** [comment]
Hey Ed

I finished writing the CAS proxy CGI script:

Test web page to create the POST data:
https://www.student.cs.uwaterloo.ca/~cs136/cas_proxy.html

The actual cgi script is here:
https://www.student.cs.uwaterloo.ca/~cs136/cgi-bin/cas_proxy.cgi

Right now it just prints the CASTGC cookie value and ST ticket value. I'm not sure what I should do with them.

Also I emailed you a testing account you can use until you're sure the CGI script is secure

**Comment by yc2lee** [comment]
Reminder to self: Output should be in json format

**Comment by yc2lee** [comment]
Hey @e45lee  I made the output be in json format.

**Comment by e45lee** [comment]
Cool great!  I'm going to close this issue then; we'll keep track of feature requests that depend on this issue in new issues.
