### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#514]

**Comment by e45lee** [comment]
Someone should review/clean up/integrate Max's code before we proceed with creating the UI for looking at old snapshots.

**Comment by YLiLarry** [comment]
UI Proposal   
![seashell-autosaves-3](https://cloud.githubusercontent.com/assets/8177295/21938976/ad16b138-d98b-11e6-8b01-a661a810f81c.png)
![seashell-autosaves-2](https://cloud.githubusercontent.com/assets/8177295/21938980/afab4166-d98b-11e6-80ca-39b342477bbf.png)
![seashell-autosaves-1](https://cloud.githubusercontent.com/assets/8177295/21938984/b296fe60-d98b-11e6-850c-f49ebf183a1d.png)

**Comment by e45lee** [comment]
I'm OK with this, so long as it can be cleanly integrated into our codebase.  I would like for any work on this to be compatible with the work I'm doing with the frontend console replacement, as that code I would like to merge in for both UI (obvious) and technical reasons (it cleans up a whole bunch of sketchy code in console.js).

**Comment by YLiLarry** [comment]
That's good point. I'll keep the compatibility with your changes in mind.

**Comment by e45lee** [comment]
This will land with the new offline mode changes.
