### ISSUE TITLE
Cannot submit if files have same name in question and common folder

### ISSUE THREAD

**Issue by yc2lee** [cs136/seashell#515]
Hey guys. Because we flatten the folders when submitting (related to a previous issue?), if the same filename exists in question and common folder, there will be a problem. 

You can reproduce the error by:

1. Creating a file called X in a question folder.
1. Create a file with the same name X in the common folder.
1. Submit the question to Marmoset from Seashell.
1. You will get that copy-file function erred because the destination path exists.

**Comment by e45lee** [comment]
I thought we weren't flattening on submit anymore.

On Apr 7, 2016 7:02 PM, "yc2lee" <notifications@github.com> wrote:
>
> Hey guys. Because we flatten the folders when submitting (related to a
previous issue?), if the same filename exists in question and common
folder, there will be a problem.
>
> You can reproduce the error by:
>
> Creating a file called X in a question folder.
> Create a file with the same name X in the common folder.
> Submit the question to Marmoset from Seashell.
> You will get that copy-file function erred because the destination path
exists.

**Comment by yc2lee** [comment]
I just get this error when submitting and I assume the hello.c that's already in seashell-marmoset-build-*** is from the question folder but i didn't check yet.

`version:     2.5.5 (stable at 9074bec)
api_version: 6
host:        ubuntu1404-008.hosts.seashell.student.cs.uwaterloo.ca
error:       Internal server error: copy-file: destination already exists
  source path: /u5/yc2lee/.seashell/projects/A10/common/hello.c
  destination path: /var/tmp/seashell-marmoset-build-14600708431460070843437/hello.c
  system error: File exists; errno=17.`

**Comment by yc2lee** [comment]
BTW I made the switch to ubuntu1404 but the problem happens on ubuntu1204 too

**Comment by e45lee** [comment]
I'm guessing this is because we haven't merged in the new branch into stable yet.  Can you try on staging/unstable?

**Comment by yc2lee** [comment]
Oh okay I tried on ugster and the problem doesn't happen. Sorry about that
