### ISSUE TITLE
Refreshing page causes compilation failure?

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#517]
Can anyone reproduce this? I'm on master. 
Compilation works only first time seashell is deployed.
After you compile anything then refresh the page, all compileAndRunProject requests return "success: false".

**Comment by Gibstick** [comment]
Is this on the latest master? It might be because of the latest changes of
mine that just got merged.

**Comment by YLiLarry** [comment]
Yes. Can you reproduce it?
It's weird. How can refreshing the page causes any problem with the backend?

**Comment by Gibstick** [comment]
Fails on c8191477c66d1c02b3965efee61c2e99527a0826 as well so I don't think it's my changes.

**Comment by Gibstick** [comment]
Works on f9e77f2. @e45lee thx

**Comment by Gibstick** [comment]
Git bisect shows badecd8 as the offending commit
