### ISSUE TITLE
Conceptual Seashell v3.0 interface proposal 

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#537]
The current Seashell Interface does not provide enough vertical space on a small screen. 

For example, on my 13' Macbook Air the editor is ridiculously small.
I spent a weekend designing a conceptual interface for Seashell. 
**The goal is to hide as much text as possible to provide editing space on a small monitor.**
(Any resolution less than 1980x1080 should be considered small.)

![seashell-v3-conceptual-editor 3](https://cloud.githubusercontent.com/assets/8177295/15131182/e0e78eee-161b-11e6-9f46-189b1849150c.jpg)
![seashell-v3-conceptual-editor](https://cloud.githubusercontent.com/assets/8177295/15130309/5cdcb1b6-1615-11e6-8e7e-aef504e8f742.jpg)
![seashell-v3-conceptual-editor 2](https://cloud.githubusercontent.com/assets/8177295/15130310/5cde10b0-1615-11e6-8987-598bdd7e11a5.jpg)

**Comment by e45lee** [comment]
This is going to be done with the new UI improvements so I'm closing this for now.
