### ISSUE TITLE
runner.rkt grabs stdout/err out of order

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#543]
Run this.
```
/**
 * Welcome to Seashell!
 */

#include <stdio.h>
#include <stdlib.h>

int func() {
    fprintf(stderr, "test");
    return 0;
}

int main(void) {
	// You can enter your code here.
    func();
	printf("Hello World!\n");
}

```

**Comment by e45lee** [comment]
There's no nice way I think to fix this in Racket, as we can't really pick up which order stdout/stderr were ready in when both stdout/stderr were ready.

Once we pull ASAN out of stderr, we can adjust the file descriptors on the program end to pipe stderr to stdout, which should fix this problem.

**Comment by e45lee** [comment]
On second thought, we need stderr distinct from stdout in order to handle tests properly.  There's no proper way to fix this.
