### ISSUE TITLE
Double the timeout for inactivity logout 

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#546]
I wonder if we can double the time that Seashell kicks users out for inactivity. I had to login multiple times during a tutorial, which is annoying. Students gave me similar feedbacks, saying that they had to relogin when doing assignments at home.

**Comment by YLiLarry** [comment]
https://piazza.com/class/in7kglm2afo29s?cid=138

**Comment by e45lee** [comment]
Can't you change the Seashell configuration file in ~cs136?  I think the option you want here is backend-client-idle-timeout

**Comment by YLiLarry** [comment]
I found "backend-client-idle-timeout" in "src/collects/seashell-config.rkt.in", don't we have to recompile the program?

**Comment by e45lee** [comment]
No, you can just modify the configuration file in
~cs136/seashell-support-files/etc/seashell_config.rkt

On Wed, May 18, 2016 at 12:34 AM, Yu Li <notifications@github.com> wrote:

> I found "backend-client-idle-timeout" in "src/collects/
> seashell-config.rkt.in", don't we have to recompile the program?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/cs136/seashell/issues/546#issuecomment-219922871>
>



-- 
Edward Lee
