### ISSUE TITLE
UBSan

### ISSUE THREAD

**Issue by michaelmior** [cs136/seashell#559]
Just wondering if [UBSan](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) has ever been considered in addition to ASAN. It's got some nice additional checks that I think could be helpful for students since we definitely don't want them doing anything which results in defined behaviour.

Consider the following program

``` C
#include <limits.h>
#include <stdio.h>

int main(void) {
  int x = INT_MAX;
  int *p = 0;
  printf("%d\n", INT_MAX + 1);
  printf("%d\n", 3/0);
  printf("%d\n", *p);
}

```

When compiled with `-fsanitize=undefined` we get the following output:

```
test.c:7:26: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int'
SUMMARY: AddressSanitizer: undefined-behavior x.c:7 
test.c:8:19: runtime error: division by zero
SUMMARY: AddressSanitizer: undefined-behavior x.c:8 
test.c:9:18: runtime error: load of null pointer of type 'int'
SUMMARY: AddressSanitizer: undefined-behavior x.c:9 
ASAN:SIGSEGV
=================================================================
==23229==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004e0e26 bp 0x7ffce5b8f7d0 sp 0x7ffce5b8f6c0 T0)
    #0 0x4e0e25  (/tmp/x+0x4e0e25)
    #1 0x7ff7c3d2b82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #2 0x435a88  (/tmp/x+0x435a88)

AddressSanitizer can not provide additional info.
==23229==ABORTING
```

This includes an error for integer overflow, division by zero, and the dereference of the null pointer (which is much nicer than the ASAN output).

**Comment by e45lee** [comment]
This was discussed this term, and the course staff decided that it would not be worth taking the time to implement this.

**Comment by michaelmior** [comment]
@e45lee That's a shame, but thanks for looking into this :)
