### ISSUE TITLE
Automatically select Marmoset project for submission

### ISSUE THREAD

**Issue by michaelmior** [cs136/seashell#560]
This used to work some time ago, but the Marmoset project corresponding to the current assignment is no longer automatically selected when students go to submit. It's not a huge deal, but it was definitely a big added convenience when this worked.

**Comment by e45lee** [comment]
This has been fixed for a while it's just that course staff haven't tested
the changes so I'm reluctant to push it out.

**Comment by michaelmior** [comment]
@e45lee Awesome. I'm happy to volunteer to help test if it can go up in staging sometimes. It seems relatively low risk. What do you anticipate could go wrong besides possibly selecting the wrong project?

**Comment by e45lee** [comment]
@michaelmior Probably nothing.  You'll want to test out unstable right now as I haven't had a chance to merge unstable-->staging.

**Comment by michaelmior** [comment]
@e45lee Checked it out with a bunch of different questions this term. It looks good to me. I also tried with a few non-assignment projects and nothing was selected (as expected).
