### ISSUE TITLE
Feature request: allow for read-only files in assignment skeletons

### ISSUE THREAD

**Issue by michaelmior** [cs136/seashell#561]
This past week in our course meeting, we discussed how students have been modifying header files provided in the assignment skeletons that they were not supposed to be changing, causing issues with Marmoset tests. It would be great if there was an option in the project settings to mark files as read-only.

I'd imagine this would work like setting the run file currently does perhaps with a lock icon next to the file and then having the editor disabled. I think this is low-priority, but it would be quite nice to have :)

**Comment by e45lee** [comment]
We could probably just use and expose the permission bits on the files themselves...We'll probably also have to switch to .tar.gz files too...

**Comment by michaelmior** [comment]
@e45lee That makes sense to me. Would probably be easier than adding new configuration options.
