### ISSUE TITLE
Standard output not being printed right away

### ISSUE THREAD

**Issue by cs136** [cs136/seashell#592]
Submitter: Tim Brecht
This program does not behave as one would expect.

Hello World! 

does not get printed until after entering an integer.

**Comment by kpalway** [comment]
There are currently some issues with output buffering so things don't get printed immediately.. this is fixed by an incoming pull request which should be live within a week.

**Comment by yc2lee** [comment]
For reference, an example program is

```
#include <stdio.h>

int main(void) {
  int x = 1234;
  printf("Hello world\n");
  scanf("%d", &x);
  printf("x = %d\n", x);
}
```
