### ISSUE TITLE
Clean up frontend build process

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#597]
Currently the frontend build process consists of handwritten Racket scripts / macro tools.  We should probably replace this with a more standard JavaScript build process.

**Comment by kpsuperplane** [comment]
would webpack be a god candidate for this?

**Comment by e45lee** [comment]
Probably, but we'd have to migrate the frontend JS to use modules, which may be a bit messy.  We should definitely talk about this next week though.

**Comment by e45lee** [comment]
This is essentially done with the new frontend, so I'm closing this for now.
