### ISSUE TITLE
Error when deleting any file

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#600]
To reproduce: just try deleting any file on seashell and you see an error.

v3.0.0

**Comment by e45lee** [comment]
This is (functionally) a cosmetic issue, and is caused by two bugs;
- We don't return any hidden files when we list a project, yet the skeleton listing CGI returns hidden files.
- restoreFileFrom chokes up if given a path in the root of the project, e.g ".project-settings.txt".
