### ISSUE TITLE
Download assignment link broken

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#601]
Cannot download assignments. The link directs to
`https://ubuntu1404-008.hosts.seashell.student.cs.uwaterloo.ca:49517/export/Sec01.zip?token=undefined`
, for example.

v3.0.0

**Comment by e45lee** [comment]
This is caused by f75dc8d.

**Comment by dtompkins** [comment]
Is this going to be fixed any time soon in production? The option that does
"nothing" is a bit annoying.

the students are really struggling with the error messages in Racket (esp.
for the uw-api project) and we want to show them how to conveniently get
their code into DrRacket.
