### ISSUE TITLE
User projects not showing up on refresh

### ISSUE THREAD

**Issue by Happytofu** [cs136/seashell#608]
When the user refreshes the Seashell main page, their projects do not show up until they hit the "refresh" button on the page.

**Comment by kpalway** [comment]
Any further instructions on how to reproduce this problem? No projects at all show up in on the page when initially loaded?

**Comment by Happytofu** [comment]
Log into seashell and use the refresh function of your browser. The page should look like the screenshot, with no projects shown, even if you have projects. Once you click the refresh button on the page, the projects show up.
![screen shot 2017-01-09 at 5 03 11 pm](https://cloud.githubusercontent.com/assets/24918727/21785471/ab3b8b78-d68d-11e6-9bc4-03bf2c622be5.png)

OS: macOS 10.11.6
Browser: Safari 9.1.2

**Comment by kpalway** [comment]
Problem does not occur for me in Chrome. Have you tried other browsers? Possibly a Safari-specific issue, I will have to try when I next have access to a Mac.

**Comment by kpalway** [comment]
One interesting thing is that in your screencap, a sync is ongoing (the "..." icon appears near the top right) so perhaps something is failing with syncing in Safari

**Comment by e45lee** [comment]
@Happytofu -- Can you check if offline mode is enabled?  We don't support Safari 9, as it's missing required functionality that we need for offline mode to work.

**Comment by Happytofu** [comment]
Offline mode was enabled.

**Comment by Happytofu** [comment]
The issue has also been reported for Safari 10.0.2.

**Comment by e45lee** [comment]
Seems to have gone away for now, so I'm closing this for now. (One possible problem is that syncing takes some time...)
