### ISSUE TITLE
UI bug on Safari: question list goes off the screen

### ISSUE THREAD

**Issue by YLiLarry** [cs136/seashell#614]
![screen shot 2017-01-12 at 3 19 31 pm](https://cloud.githubusercontent.com/assets/8177295/21906777/b289186a-d8da-11e6-8394-617db67e95ee.png)
![screen shot 2017-01-12 at 3 26 33 pm](https://cloud.githubusercontent.com/assets/8177295/21906976/8dd58908-d8db-11e6-8ce3-499ce0febf46.png)

**Comment by e45lee** [comment]
Is this the case with Chrome?  They're both based off of the same rendering engine (WebKit).

**Comment by YLiLarry** [comment]
diagnosis: the css was using word-spacing to separate buttons while safari does not count word-spacing into container width.
