### ISSUE TITLE
Exporting project (templates) with metadata (runner files, read only files)

### ISSUE THREAD

**Issue by e45lee** [cs136/seashell#767]
We currently export projects without their settings -- runner files, possibly list of files that are read only.
This wasn't a problem before as project settings were stored in a plain text hidden file in the filesystem,
and read only files were indicated with a Racket/C comment in their contents.

We should figure out a way to store this metadata when we export a project (for students to use as a template), and a way to apply this metadata when we import a template for a project.

One idea is to have a special METADATA file which will store this, which we generate on export and load/apply on import.  It would also be nice if this file was human readable/write-able to support
manually generated Seashell templates.

**Comment by kpalway** [comment]
We could look for a .metadata hidden file (doesn't have to be hidden I guess) that stores s-expression pairs like this:

((read_only . ("q1/llist.h" "common/readchar.c"))
 (q1_runner_file . "q1/main.c"))

This is similar to how the .project-settings.txt file worked in the old Seashell.
