### ISSUE TITLE
Full screen editor mode

### ISSUE THREAD

**Issue by kpalway** [cs136/seashell#784]
Looks like this was never implemented in the UI overhaul. Monaco does not seem to have a built-in implementation of this either. Should do this to address instructor's concerns, pasted below:

I just logged in and in terms of the interface, it seems to have
gone back to using up a lot of space at the top of the screen.
Remember that for use in the classroom we really want to eliminate
all of that extra white space at the top.

That extra space costs us about 2-3 lines of code that won’t fit
on the screen.

**Comment by YLiLarry** [comment]
What did he mean by the space at the top of the screen? I don't see it on my build.

**Comment by kpalway** [comment]
I assume he means the 40-50 pixels the menu bar takes up

**Comment by e45lee** [comment]
The navigation bar uses ~42-43 pixels worth of space.  I don't think it's worth adding a feature just for 1 line of code, especially as we are wrapping this project up.
