### ISSUE TITLE
List of files doesn't refresh when switching projects that don't have files opened

### ISSUE THREAD

**Issue by yc2lee** [cs136/seashell#816]
If you are viewing a question with no files open (so it shows a list of files) and switch to another question that also has no files open, it will not refresh the list of available files.  If you click on one of the files from the previously-open question, Seashell returns to the project selection screen.

**Comment by e45lee** [comment]
The file list component binds the question/project in its constructor, so it doesn't pick up the changes when the state is updated.

Just refer to the question/project in the List component render function.
